### PR TITLE
Replace Popen calls to nmcli with api calls to the Python GI API

### PR DESCRIPTION
**Pull request by He-Ro**
With this rather thorough rewrite of nmcli-dmenu almost all calls to nmcli have been eliminated and been replaced with calls to the Python GI API (https://lazka.github.io/pgi-docs/#NM-1.0)

This requires PyGObjects (https://wiki.gnome.org/Projects/PyGObject), which should be widely available.
The upside to this is a decrease in execution time.
For me the execution time, before dmenu (or in my place rofi) is displayed is decreased from ~3.0 seconds to ~ 0.5 seconds. Which is quite noticeable.
Please be free to ask about the changes, I tried to make it behave in the same way as before.
I could not test the GSM part or multiple WiFi adapters!

### CODE REVIEW

**Comment by firecat53** [comment]
Wow, thanks! We just moved, so I'll need a little time to digest this. I wonder if most people will be ok with the extra dependency or if I should leave the original version as a separate branch. Since NetworkManager typically implies other GTK libraries installed, I can't imagine too many people worrying over one more relatively small package.

It is noticeable faster! Nice work!

**Comment by firecat53** [comment]
I made some relatively minor changes...disregard the duplicate commits above, I was trying something and did a force push.

Looks like the only function that remains to be rewritten using gobject is set_new_connection(). Are you already working on that?

Did you work directly from the documentation or were there some examples to get you started? This gobject stuff is not intuitive for me for me at all!!

**Comment by He-Ro** [comment]
I have not started to rewrite that last function. First wanted to show my progress and wait for feedback.

Some small example scripts can be found here: https://cgit.freedesktop.org/NetworkManager/NetworkManager/tree/examples/python/gi

From those I took two small functions. I am not versed in Licences so I am not sure if this is okay or needs attribution.

I have to agree with you, that the API first seems quite complex. Especially the difference between an active and a normal connection weren't clear to me at first.

The introduction of the Action class was however not needed by the API, but this way it seems cleaner, to me at least ;)

**Comment by firecat53** [comment]
I went ahead and merged this with a few more minor fixes. I'll leave the PR open until one of us finishes the set_new_connection() function. Thanks!

**Comment by firecat53** [comment]
Initial take on set_new_connection() with GObject. Seems to work. Going to test more in different places. Any other testers would be welcome. Branch He-Ro-Master.

**Comment by He-Ro** [comment]
Awesome, that you merged it. I briefly tested the new code for connecting to new networks. What I found is, that when leaving the password empty for a WPA2 connection (where there is a minimum length for the key) this is still acepted and a connection with this too short password is created. Now trying to connect to this network is no longer possible from nmcli-dmenu, because now the existing connection is used. Maybe one could delete the connection, if the connection was not established correctly?

**Comment by firecat53** [comment]
Ooops, I actually had code in there originally that did exactly that! Forgot to port it to the GObject code. Thanks!

**Comment by He-Ro** [comment]
I do not know, how you implemented that functionality, but this verification (https://lazka.github.io/pgi-docs/NetworkManager-1.0/classes/Connection.html#NetworkManager.Connection.verify) seems like a good starting point. It can check, whether the settings are valid, before even adding the connection (as far, as I understand it).

**Comment by firecat53** [comment]
Ok, implemented a verify_conn function to check validity and remove the connection on errors. Can you test it and let me know if it works for you as well (Hero-Ro-master branch)? Seems functional here so far. I'm a little concerned that on a connection that negotiates the passphrase more slowly that the verify_conn checks may miss a passphrase error.

Thanks!

**Comment by He-Ro** [comment]
It seems to work for me in a quick test. The connection is not added to network manager and thus after a failed attempt, I can try to connect to the same wifi again.

**Comment by firecat53** [comment]
Cool. I consolidated all the AP list creation/filtering into one function and merged. Thanks again for doing this!!

**Pull request closed without merging**
