### PR TITLE
pretty output. fixed sort, unique ssids and locales

### PR DESCRIPTION
**Pull request by kirill9617**
screenshot_11 10 2015_scrot

### CODE REVIEW

**Comment by firecat53** [comment]
Great work on this commit!! I appreciate it! Other than the question above about the locale/LANG issue, I've just got a few PEP-8 fixes.

Thanks!
Scott

**Comment by kirill9617** [comment]
Sorry for PEP-8 errors, I am not Python developer =)

**Comment by firecat53** [comment]
Give that c995e05 a try. It sets the locale to 'C' at the start...I just can't tell if it'll work for you or not! :)

**Comment by firecat53** [comment]
Give the kirill9617-master branch another try. I tried a different approach. If it works, can you cycle through all the possible actions (add network, add network with passphrase, toggle network, toggle VPN, etc.) to make sure I didn't mix up where the 'C' language should be set?

Thanks!

**Comment by firecat53** [comment]
Ok, #12 is merged. Does this branch work for you now with no encoding/locale errors? Thanks very much for working on this today!! Any other suggestions/fixes before we merge this?

Scott

**Comment by firecat53** [comment]
I'm going to go ahead and merge the kirill9617-master branch into master, as it is working here. If there are problems you haven't found or had time to report yet, just open a new issue and we'll squash them as they come.

Thanks again for your interest and assistance!!

Scott

**Pull request closed without merging**
